super_fit/super_fit/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from walk import views as walk_view
from diet import views as diet_view
from django.contrib.auth import views as auth_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workout.urls')),
    path('login/', auth_view.LoginView.as_view(template_name='user/login.html'),
         name='user-login'),
    path('register/', user_view.register, name='user-register'),
    path('profile/', user_view.profile, name='user-profile'),
    path('profile/update/', user_view.profile_update, name='user-profile-update'),
    path('logout/', auth_view.LogoutView.as_view(template_name='home/index_demo.html'),
         name='user-logout'),
    path('walks/', walk_view.walks, name='walk-index'),
    path('diet/', diet_view.diet, name='diet-index'),
]

super_fit/workout/urls.py
from django.urls import path
from . import views


urlpatterns = [    
    
    path('demo/', views.index_demo, name='home-index-demo' ),
    path('', views.index, name='home-index' ),
    path('workouts/', views.w_index, name='workout-index')
]

super_fit/user/models.py
from django.db import models
from django.contrib.auth.models import User
from .validations import validate_positive


TASK = (
    ('get slim', 'get slim'),
    ('get save', 'get save'),
    ('get save','get grow'),
)
LIFESTYLE = (
    ('Sedentary', 'Sedentary'),
    ('Active','Active'),
    ('Sports', 'Sports'),
)

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)

class Profile(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=50, null=True)
    weight = models.FloatField(null=True, validators=[validate_positive], error_messages={'required': 'Please enter positive number'})
    task = models.CharField(max_length=10, choices=TASK, null=True)    
    goal = models.FloatField(null=True, validators=[validate_positive], error_messages={'required': 'Please enter positive number'})
    lifestyle = models.CharField(max_length=15, choices=LIFESTYLE, null=True)
    gender = models.CharField(max_length=10, choices=GENDER, blank='Male')
    diet = models.PositiveIntegerField(null=True)
    age = models.PositiveIntegerField(null=True)
    growth = models.PositiveIntegerField(null=True)

    def __str__(self):
        return f'{self.name} - {self.task}'

super_fit/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class CreateUserForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address', 'lifestyle', 'gender', 'weight', 'task', 'goal', 'age', 'growth']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     try:
    #         kfa ={                               
    #             'Sedentary': 1.0, 
    #             'Active': 1.3,
    #             'Sports':1.5                
    #             }
    #         if self.model.gender == 'Female':
    #             if self.age < 30:
    #                 self.diet = int((0.062 * self.goal + 2.036) * 240 * kfa[self.lifestyle])
    #             elif 31< self.age <60:
    #                 self.diet = int((0.034 * self.goal + 3.538) * 240 * kfa[self.lifestyle])
    #             else:
    #                 self.diet = int((0.038 * self.goal + 2.755) * 240 * kfa[self.lifestyle])
    #         else:
    #             if self.age < 30:
    #                 self.diet = int((0.063 * self.goal + 2.896) * 240 * kfa[self.lifestyle])
    #             elif 31< self.age <60:
    #                 self.diet = int((0.0484 * self.goal + 3.653) * 240 * kfa[self.lifestyle])
    #             else:
    #                 self.diet = int((0.0491 * self.goal + 2.459) * 240 * kfa[self.lifestyle])
            

    #         pass
    #     except ValueError as e:
    #         self.diet = 2000

super_fit/user/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from .forms import UpdateUserForm, UpdateProfileForm
from workout.utilits import DailyTaskDemo


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user-login')
    else:
        form = UserCreationForm()
    context = {
        'form' : form,
    }

    return render(request, template_name='user/login.html', context=context)


def profile(request):
    return render(request, template_name='user/profile.html')


def profile_update(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('user-profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
    
    context = {
        'user_form' : user_form,
        'profile_form' : profile_form,
    }


    return render(request, template_name='user/profile_update.html', context=context)

super_fit/templates/user/login.html
{% extends 'partials/base.html' %}

{% block title %} Quick|start Log in {% endblock%}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row mt-5 row-cols-1 row-cols-mt-5 ">
        <div class="col-md-6 offset-md-3">
            <div class="card mb-4 rounded-3 dark-sm">
                <div class="card-header bg-dark py-3">
                    <h4 class="my-0 fw-normal text-white text-center">Log in</h4>
                </div>
                <div class="card-body">
                    <form method="POST">

                        {% csrf_token %}

                        {{form | crispy}}

                        <hr>
                        <input class="btn btn-succes bg-dark text-white" type="submit" value="Log in">
                    </form>

                    
                    </div>          
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

super_fit/templates/user/profile.html
{% extends 'partials/base.html' %}

{% block title %} Quick|start Log in {% endblock%}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row mt-5 row-cols-1 row-cols-mt-5 ">
        <div class="col-md-6 offset-md-3">
            <div class="card mb-4 rounded-3 dark-sm">
                <div class="card-header bg-dark py-3">
                  <h4 class="my-0 fw-normal text-white text-center">Profile</h4>
                </div>                          
                <div class="card-body"> 
                    <div class="container">
                        <div class="row">
                            <div class="col align-self-start">
                                <button class="btn btn-succes bg-dark text-white" value=""><a href="{% url 'user-profile-update'  %}" class="nav-link active bg-dark text-white">Edit</a>
                            </div>
                            <div class="col"></div>
                            <div class="col"></div>
                            <div class="col"></div>
                            <div class="col"></div>
                            <div class="col align-self-end">
                                <button class="btn btn-succes bg-dark text-white" value=""><a href="{% url 'user-logout' %}" class="nav-link active bg-dark text-white">Logout</a>
                            </div>
                        </div>
                    </div>                                                   
                        <hr>
                        <div class="alert alert-dark" role="alert">
                            Personal information  
                        </div>
                        <table class="table bg-white table-borderless">
                            <tbody>
                                <th scope="row">Name</th> <td>{{ user.username }} </td> </tr>
                                <th scope="row">Email</th> <td>{{ user.email }}</td> </tr>  
                                <th scope="row">Address for daily walk</th> <td>{{ user.profile.address }}</td> </tr> 
                                <th scope="row">Gender</th> <td>{{ user.profile.gender }} </td> </tr>   
                                <th scope="row">Age</th> <td>{{ user.profile.age }} </td>  </tr>   
                                <th scope="row">Growth</th> <td>{{ user.profile.growth }} cm </td>  </tr>                             
                               
                              
                                <th scope="row">Weight</th> <td>{{ user.profile.weight }} kg</td> </tr>    
                                <th scope="row">Lifestyle</th> <td>{{ user.profile.lifestyle }}</td> </tr>  
                            </tbody>
                        </table> 
                        <hr>
                        <div class="alert alert-dark" role="alert">
                            Personal goals
                        </div>
                            <table class="table bg-white table-borderless">
                                <tbody>              
                                    <th scope="row">Task</th> <td>{{ user.profile.task }} </td> </tr>                                 
                                    <th scope="row">Goal</th> <td>{{ user.profile.goal }} kg</td> </tr> 
                                    <th scope="row">Diet</th> <td>{{ user.profile.diet }} kcal.</td> </tr> 
                                </tbody>
                            </table>                            
                            <a class="nav-link text-white" href="{% url 'user-logout' %}">Logout</a>
                        </div> 
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}      

super_fit/templates/user/profile_update.html
{% extends 'partials/base.html' %}

{% block title %} Quick|start Log in {% endblock%}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row mt-5 row-cols-1 row-cols-mt-5 ">
        <div class="col-md-6 offset-md-3">
            <div class="card mb-4 rounded-3 dark-sm">
                <div class="card-header bg-dark py-3">
                  <h4 class="my-0 fw-normal text-white text-center">Edit profile</h4>
                </div>                          
                <div class="card-body"> 
                    <div class="container">
                        <div class="row">
                            <div class="container">
                                <form method="post">                                    

                                    {% csrf_token %}
                                    {{ user_form| as_crispy_errors }}
                                    {{ profile_form| as_crispy_errors }}

                                    <div class="alert alert-dark" role="alert">
                                        Personal information  
                                    </div>
                                    <table class="table bg-white table-borderless">
                                        <tbody>
                                            <th scope="row">Name</th> <td>{{ user_form.username }} </td> </tr> 
                                            <th scope="row">Address for daily walk</th> <td>{{ profile_form.address }}</td> </tr> 
                                            <th scope="row">Email</th> <td>{{ user_form.email }}</td> </tr> 
                                            <th scope="row">Gender</th> <td>{{ profile_form.gender }} </td> </tr>   
                                            <th scope="row">Age</th> <td>{{ profile_form.age }} </td>  </tr>   
                                            <th scope="row">Growth</th> <td>{{ profile_form.growth }} cm </td>  </tr>                             
                                            
                                            
                                            <th scope="row">Weight</th> <td>{{ profile_form.weight }} kg</td> </tr>    
                                            <th scope="row">Lifestyle</th> <td>{{ profile_form.lifestyle }}</td> </tr>  
                                        </tbody>
                                    </table> 
                                    <hr>
                                    <div class="alert alert-dark" role="alert">
                                        Personal goals
                                    </div>
                                        <table class="table bg-white table-borderless">
                                            <tbody>              
                                                <th scope="row">Task</th> <td>{{ profile_form.task }} </td> </tr>                                 
                                                <th scope="row">Goal</th> <td>{{ profile_form.goal }} kg</td> </tr> 
                                            </tbody>
                                        </table>                  

                                    <!-- {{ user_form| as_crispy_errors }}
                                    {{ profile_form| as_crispy_errors }}


                                    {{ user_form | crispy }}

                                    {{ profile_form | crispy }} -->
                                    
                                    <hr>
                                    <input class="btn btn-succes bg-dark text-white" type="submit" value="Save">
                                </form>
                            </div>
                            </div>
                        </div>
                    </div>                            
                    <a class="nav-link text-white" href="{% url 'user-logout' %}">Logout</a>                        
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}      

super_fit/templates/user/register.html
{% extends 'partials/base.html' %}

{% block title %} Quick|start Register {% endblock%}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row mt-5 row-cols-1 row-cols-mt-5 ">
        <div class="col-md-6 offset-md-3">
            <div class="card mb-4 rounded-3 dark-sm">
                <div class="card-header bg-dark py-3">
                  <h4 class="my-0 fw-normal text-white text-center">Register</h4>
                </div>                  
                <div class="card-body">
                    <form method="POST">

                        {% csrf_token %}

                        {{form | crispy}}

                        <hr>
                        <input class="btn btn-succes bg-dark text-white" type="submit" value="Register">
                    </form>               
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}                

super_fit/templates/user/test.html
<div class="container">
    <form method="post">
<div id="div_id_username" class="form-group"> <label for="id_username" class=" requiredField">
Username<span class="asteriskField">*</span> </label> <div> <input type="text" name="username" value="qwe" maxlength="150" class="textinput textInput form-control" required="" id="id_username"> <small id="hint_id_username" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small> </div> </div> <div id="div_id_email" class="form-group"> <label for="id_email" class="">
Email address
</label> <div> <input type="email" name="email" value="qw@qw.qw" maxlength="254" class="emailinput form-control" id="id_email"> </div> </div>
        

<div id="div_id_address" class="form-group"> <label for="id_address" class=" requiredField">
Address<span class="asteriskField">*</span> </label> <div> <input type="text" name="address" value="sd" maxlength="50" class="textinput textInput form-control" required="" id="id_address"> </div> </div> <div id="div_id_lifestyle" class="form-group"> <label for="id_lifestyle" class=" requiredField">
Lifestyle<span class="asteriskField">*</span> </label> <div> <select name="lifestyle" class="select form-control" required="" id="id_lifestyle"> <option value="">---------</option> <option value="Sedentary" selected="">Sedentary</option> <option value="Active">Active</option> <option value="Sports">Sports</option>    

</select> </div> </div> <div id="div_id_gender" class="form-group"> <label for="id_gender" class=" requiredField">
Gender<span class="asteriskField">*</span> </label> <div> <select name="gender" class="select form-control" required="" id="id_gender"> <option value="">---------</option> <option value="Male" selected="">Male</option> <option value="Female">Female</option>

</select> </div> </div> <div id="div_id_weight" class="form-group"> <label for="id_weight" class=" requiredField">
Weight<span class="asteriskField">*</span> </label> <div> <input type="number" name="weight" value="-1.0" step="any" class="numberinput form-control" required="" id="id_weight"> </div> </div> <div id="div_id_task" class="form-group"> <label for="id_task" class=" requiredField">
Task<span class="asteriskField">*</span> </label> <div> <select name="task" class="select form-control" required="" id="id_task"> <option value="">---------</option> <option value="get slim" selected="">get slim</option> <option value="get save">get save</option> <option value="get save">get grow</option>

</select> </div> </div> <div id="div_id_goal" class="form-group"> <label for="id_goal" class=" requiredField">
Goal<span class="asteriskField">*</span> </label> <div> <input type="number" name="goal" value="1.0" step="any" class="numberinput form-control" required="" id="id_goal"> </div> </div>

        
        <hr>
        <input class="btn btn-succes bg-dark text-white" type="submit" value="Save">
    </form>
</div>